{
  "technicalQuestions": [
    "question",
    "How do you handle dynamic content and CAPTCHAs when scraping websites using Selenium and BeautifulSoup?",
    "intention",
    "To evaluate the candidate's understanding of different web scraping techniques and their ability to solve common automation challenges.",
    "answer",
    "Selenium is used for dynamic content that requires JavaScript execution by simulating a browser, while BeautifulSoup is better for parsing static HTML efficiently. For CAPTCHAs, I would suggest using services like 2Capcha or implementing headful browsing with delays to mimic human behavior, though scraping is best performed on sites that provide an API.",
    "question",
    "In your Contextual WhatsApp Bot, how did you manage the prompt engineering for the Gemini 1.5 Flash API to ensure responses remain consistent?",
    "intention",
    "To assess practical experience with LLM integration and prompt optimization.",
    "answer",
    "I utilized system instructions to define the bot's persona and context. I also implemented a context window by storing the last few messages in a list to provide the API with short-term memory, ensuring the conversation remains coherent and relevant.",
    "question",
    "Explain the difference between PyAutoGUI and Selenium for UI automation. When would you choose one over the other?",
    "intention",
    "To check the candidate's knowledge of automation tool selection based on the environment.",
    "answer",
    "Selenium is specifically for web browsers and interacts with DOM elements, making it robust against UI shifts. PyAutoGUI controls the mouse and keyboard at the OS level using pixel coordinates, making it suitable for desktop applications where no DOM is available, but it is more sensitive to screen resolution changes."
  ],
  "behaviorQuestions": [
    "question",
    "Describe a significant technical challenge you faced while developing 'JARVIS' and how you overcame it.",
    "intention",
    "To understand the candidate's problem-solving process and persistence.",
    "answer",
    "I faced issues with background noise interference during speech recognition. I resolved this by implementing energy threshold adjustments in the SpeechRecognition library and adding a 'calibrating' phase to filter ambient noise before processing commands.",
    "question",
    "As an intern, how would you handle a situation where a script you deployed into an internal tool breaks an existing workflow?",
    "intention",
    "To evaluate accountability and incident management skills.",
    "answer",
    "I would immediately notify the supervisor, roll back the changes to the last stable version to minimize downtime, and then conduct a root cause analysis in a local environment to fix the bug before redeploying with better test coverage."
  ],
  "skillGaps": [
    "skill",
    "Backend Web Frameworks (FastAPI/Flask)",
    "level",
    "medium",
    "skill",
    "Database Management (SQL/NoSQL)",
    "level",
    "high",
    "skill",
    "Unit Testing (PyTest/Unittest)",
    "level",
    "medium"
  ],
  "preperationPlan": [
    "day",
    1,
    "focus",
    "Deep dive into Python Advanced concepts: Decorators, Generators, and Concurrency (AsyncIO) for better automation performance.",
    "day",
    2,
    "focus",
    "Learn FastAPI basics to understand how to wrap Python automation scripts into accessible REST APIs.",
    "day",
    3,
    "focus",
    "Study API security best practices, specifically environment variable management and OAuth2 authentication.",
    "day",
    4,
    "focus",
    "Hands-on practice with Pandas: Master DataFrames, GroupBy operations, and data cleaning for complex scraping outputs.",
    "day",
    5,
    "focus",
    "Implement Unit Testing in existing projects using PyTest to demonstrate code reliability.",
    "day",
    6,
    "focus",
    "Review System Design basics: How to scale an automation script into a distributed system using message queues like Celery.",
    "day",
    7,
    "focus",
    "Mock Interviews focusing on project walkthroughs and explaining the technical architecture of the WhatsApp and JARVIS projects."
  ]
}
